baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Denis Mittakarin'
theme = 'PaperMod'

[params]
  ShowBreadCrumbs = true
  ShowToc = true
  ShowCodeCopyButtons = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "/resume/"
  weight = 3
